spring.application.name=OfferLetter
server.port=8080

# PDF Configuration
pdf.font.directory=classpath:/fonts/
pdf.template.directory=classpath:/templates/

# Logging
logging.level.com.itextpdf=WARN
logging.level.com.fis.offer=DEBUG
